import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

Future<Country?> showCountryPicker({required BuildContext context, String? title}) async {
  try {
    final response = await rootBundle.loadString("asset/data/countries.json");
    final countries = await json.decode(response);

    return showDialog<Country?>(
        barrierColor: Colors.black.withOpacity(0.9),
        // ignore: use_build_context_synchronously
        context: context,
        builder: (context) => Dialog(
            insetPadding: const EdgeInsets.all(60),
            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
            child: Column(children: [
              Container(padding: const EdgeInsets.symmetric(vertical: 20), child: Text(title ?? "Select country")),
              Expanded(
                  child: ListView.builder(
                shrinkWrap: true,
                itemCount: countries.length,
                itemBuilder: (context, i) => ListTile(
                  leading: Text(countries[i]["code"]),
                  title: Text(countries[i]["name"]),
                  onTap: () {
                    Navigator.of(context).pop(Country(name: countries[i]["name"], code: countries[i]["code"]));
                  },
                ),
              ))
            ])));
  } catch (e) {
    return showDialog(
        // ignore: use_build_context_synchronously
        context: context,
        builder: (context) => AlertDialog(
              title: const Text("Error!"),
              icon: const Icon(Icons.error_outlined, color: Colors.red),
              content: Text(e.toString()),
              actions: [TextButton(onPressed: () => Navigator.of(context).pop(null), child: const Text("Ok"))],
            ));
  }
}

class Country {
  Country({required this.name, required this.code});

  String name;
  String code;
}

extension CountryExtension on Country? {
  String get name => this == null ? "United States" : this!.name;
  String get code => this == null ? "US" : this!.code;
}

/*
// ignore: non_constant_identifier_names
final List<Country> COUNTRIES = [
  Country.fromJson({"name": "Afghanistan", "code": "AF"}),
  Country.fromJson({"name": "Åland Islands", "code": "AX"}),
  Country.fromJson({"name": "Albania", "code": "AL"},
  Country.fromJson({"name": "Algeria", "code": "DZ"},
  Country.fromJson({"name": "American Samoa", "code": "AS"},
  Country.fromJson({"name": "AndorrA", "code": "AD"},
  Country.fromJson({"name": "Angola", "code": "AO"},
  Country.fromJson({"name": "Anguilla", "code": "AI"},
  Country.fromJson({"name": "Antarctica", "code": "AQ"},
  Country.fromJson({"name": "Antigua and Barbuda", "code": "AG"},
  Country.fromJson({"name": "Argentina", "code": "AR"},
  Country.fromJson({"name": "Armenia", "code": "AM"},
  Country.fromJson({"name": "Aruba", "code": "AW"},
  Country.fromJson({"name": "Australia", "code": "AU"},
  Country.fromJson({"name": "Austria", "code": "AT"},
  Country.fromJson({"name": "Azerbaijan", "code": "AZ"},
  Country.fromJson({"name": "Bahamas", "code": "BS"},
  Country.fromJson({"name": "Bahrain", "code": "BH"},
  Country.fromJson({"name": "Bangladesh", "code": "BD"},
  Country.fromJson({"name": "Barbados", "code": "BB"},
  Country.fromJson({"name": "Belarus", "code": "BY"},
  Country.fromJson({"name": "Belgium", "code": "BE"},
  Country.fromJson({"name": "Belize", "code": "BZ"},
  Country.fromJson({"name": "Benin", "code": "BJ"},
  Country.fromJson({"name": "Bermuda", "code": "BM"},
  Country.fromJson({"name": "Bhutan", "code": "BT"},
  Country.fromJson({"name": "Bolivia", "code": "BO"},
  Country.fromJson({"name": "Bosnia and Herzegovina", "code": "BA"},
  Country.fromJson({"name": "Botswana", "code": "BW"},
  Country.fromJson({"name": "Bouvet Island", "code": "BV"},
  Country.fromJson({"name": "Brazil", "code": "BR"},
  Country.fromJson({"name": "British Indian Ocean Territory", "code": "IO"},
  Country.fromJson({"name": "Brunei Darussalam", "code": "BN"},
  Country.fromJson({"name": "Bulgaria", "code": "BG"},
  Country.fromJson({"name": "Burkina Faso", "code": "BF"},
  Country.fromJson({"name": "Burundi", "code": "BI"},
  Country.fromJson({"name": "Cambodia", "code": "KH"},
  Country.fromJson({"name": "Cameroon", "code": "CM"},
  Country.fromJson({"name": "Canada", "code": "CA"},
  Country.fromJson({"name": "Cape Verde", "code": "CV"},
  Country.fromJson({"name": "Cayman Islands", "code": "KY"},
  Country.fromJson({"name": "Central African Republic", "code": "CF"},
  Country.fromJson({"name": "Chad", "code": "TD"},
  Country.fromJson({"name": "Chile", "code": "CL"},
  Country.fromJson({"name": "China", "code": "CN"},
  Country.fromJson({"name": "Christmas Island", "code": "CX"},
  Country.fromJson({"name": "Cocos (Keeling) Islands", "code": "CC"},
  Country.fromJson({"name": "Colombia", "code": "CO"},
  Country.fromJson({"name": "Comoros", "code": "KM"},
  Country.fromJson({"name": "Congo", "code": "CG"},
  Country.fromJson({"name": "Congo, The Democratic Republic of the", "code": "CD"},
  Country.fromJson({"name": "Cook Islands", "code": "CK"},
  Country.fromJson({"name": "Costa Rica", "code": "CR"},
  Country.fromJson({"name": "Croatia", "code": "HR"},
  Country.fromJson({"name": "Cuba", "code": "CU"},
  Country.fromJson({"name": "Cyprus", "code": "CY"},
  Country.fromJson({"name": "Czech Republic", "code": "CZ"},
  Country.fromJson({"name": "Denmark", "code": "DK"},
  Country.fromJson({"name": "Djibouti", "code": "DJ"},
  Country.fromJson({"name": "Dominica", "code": "DM"},
  Country.fromJson({"name": "Dominican Republic", "code": "DO"},
  Country.fromJson({"name": "Ecuador", "code": "EC"},
  Country.fromJson({"name": "Egypt", "code": "EG"},
  Country.fromJson({"name": "El Salvador", "code": "SV"},
  Country.fromJson({"name": "Equatorial Guinea", "code": "GQ"},
  Country.fromJson({"name": "Eritrea", "code": "ER"},
  Country.fromJson({"name": "Estonia", "code": "EE"},
  Country.fromJson({"name": "Ethiopia", "code": "ET"},
  Country.fromJson({"name": "Falkland Islands (Malvinas)", "code": "FK"},
  Country.fromJson({"name": "Faroe Islands", "code": "FO"},
  Country.fromJson({"name": "Fiji", "code": "FJ"},
  Country.fromJson({"name": "Finland", "code": "FI"},
  Country.fromJson({"name": "France", "code": "FR"},
  Country.fromJson({"name": "French Guiana", "code": "GF"},
  Country.fromJson({"name": "French Polynesia", "code": "PF"},
  Country.fromJson({"name": "French Southern Territories", "code": "TF"},
  Country.fromJson({"name": "Gabon", "code": "GA"},
  Country.fromJson({"name": "Gambia", "code": "GM"},
  Country.fromJson({"name": "Georgia", "code": "GE"},
  Country.fromJson({"name": "Germany", "code": "DE"},
  Country.fromJson({"name": "Ghana", "code": "GH"},
  Country.fromJson({"name": "Gibraltar", "code": "GI"},
  Country.fromJson({"name": "Greece", "code": "GR"},
  Country.fromJson({"name": "Greenland", "code": "GL"},
  Country.fromJson({"name": "Grenada", "code": "GD"},
  Country.fromJson({"name": "Guadeloupe", "code": "GP"},
  Country.fromJson({"name": "Guam", "code": "GU"},
  Country.fromJson({"name": "Guatemala", "code": "GT"},
  Country.fromJson({"name": "Guernsey", "code": "GG"},
  Country.fromJson({"name": "Guinea", "code": "GN"},
  Country.fromJson({"name": "Guinea-Bissau", "code": "GW"},
  Country.fromJson({"name": "Guyana", "code": "GY"},
  Country.fromJson({"name": "Haiti", "code": "HT"},
  Country.fromJson({"name": "Heard Island and Mcdonald Islands", "code": "HM"},
  Country.fromJson({"name": "Holy See (Vatican City State)", "code": "VA"},
  Country.fromJson({"name": "Honduras", "code": "HN"},
  Country.fromJson({"name": "Hong Kong", "code": "HK"},
  Country.fromJson({"name": "Hungary", "code": "HU"},
  Country.fromJson({"name": "Iceland", "code": "IS"},
  Country.fromJson({"name": "India", "code": "IN"},
  Country.fromJson({"name": "Indonesia", "code": "ID"},
  Country.fromJson({"name": "Iran", "code": "IR"},
  Country.fromJson({"name": "Iraq", "code": "IQ"},
  Country.fromJson({"name": "Ireland", "code": "IE"},
  Country.fromJson({"name": "Isle of Man", "code": "IM"},
  Country.fromJson({"name": "Israel", "code": "IL"},
  Country.fromJson({"name": "Italy", "code": "IT"},
  Country.fromJson({"name": "Jamaica", "code": "JM"},
  Country.fromJson({"name": "Japan", "code": "JP"},
  Country.fromJson({"name": "Jersey", "code": "JE"},
  Country.fromJson({"name": "Jordan", "code": "JO"},
  Country.fromJson({"name": "Kazakhstan", "code": "KZ"},
  Country.fromJson({"name": "Kenya", "code": "KE"},
  Country.fromJson({"name": "Kiribati", "code": "KI"},
  Country.fromJson({"name": "Korea, Republic of", "code": "KR"},
  Country.fromJson({"name": "Kuwait", "code": "KW"},
  Country.fromJson({"name": "Kyrgyzstan", "code": "KG"},
  Country.fromJson({"name": "Laos", "code": "LA"},
  Country.fromJson({"name": "Latvia", "code": "LV"},
  Country.fromJson({"name": "Lebanon", "code": "LB"},
  Country.fromJson({"name": "Lesotho", "code": "LS"},
  Country.fromJson({"name": "Liberia", "code": "LR"},
  Country.fromJson({"name": "Libya", "code": "LY"},
  Country.fromJson({"name": "Liechtenstein", "code": "LI"},
  Country.fromJson({"name": "Lithuania", "code": "LT"},
  Country.fromJson({"name": "Luxembourg", "code": "LU"},
  Country.fromJson({"name": "Macao", "code": "MO"},
  Country.fromJson({"name": "North Macedonia", "code": "MK"},
  Country.fromJson({"name": "Madagascar", "code": "MG"},
  Country.fromJson({"name": "Malawi", "code": "MW"},
  Country.fromJson({"name": "Malaysia", "code": "MY"},
  Country.fromJson({"name": "Maldives", "code": "MV"},
  Country.fromJson({"name": "Mali", "code": "ML"},
  Country.fromJson({"name": "Malta", "code": "MT"},
  Country.fromJson({"name": "Marshall Islands", "code": "MH"},
  Country.fromJson({"name": "Martinique", "code": "MQ"},
  Country.fromJson({"name": "Mauritania", "code": "MR"},
  Country.fromJson({"name": "Mauritius", "code": "MU"},
  Country.fromJson({"name": "Mayotte", "code": "YT"},
  Country.fromJson({"name": "Mexico", "code": "MX"},
  Country.fromJson({"name": "Micronesia, Federated States of", "code": "FM"},
  Country.fromJson({"name": "Moldova", "code": "MD"},
  Country.fromJson({"name": "Monaco", "code": "MC"},
  Country.fromJson({"name": "Mongolia", "code": "MN"},
  Country.fromJson({"name": "Montserrat", "code": "MS"},
  Country.fromJson({"name": "Morocco", "code": "MA"},
  Country.fromJson({"name": "Mozambique", "code": "MZ"},
  Country.fromJson({"name": "Myanmar", "code": "MM"},
  Country.fromJson({"name": "Namibia", "code": "NA"},
  Country.fromJson({"name": "Nauru", "code": "NR"},
  Country.fromJson({"name": "Nepal", "code": "NP"},
  Country.fromJson({"name": "Netherlands", "code": "NL"},
  Country.fromJson({"name": "Netherlands Antilles", "code": "AN"},
  Country.fromJson({"name": "New Caledonia", "code": "NC"},
  Country.fromJson({"name": "New Zealand", "code": "NZ"},
  Country.fromJson({"name": "Nicaragua", "code": "NI"},
  Country.fromJson({"name": "Niger", "code": "NE"},
  Country.fromJson({"name": "Nigeria", "code": "NG"},
  Country.fromJson({"name": "Niue", "code": "NU"},
  Country.fromJson({"name": "Norfolk Island", "code": "NF"},
  Country.fromJson({"name": "Northern Mariana Islands", "code": "MP"},
  Country.fromJson({"name": "Norway", "code": "NO"},
  Country.fromJson({"name": "Oman", "code": "OM"},
  Country.fromJson({"name": "Pakistan", "code": "PK"},
  Country.fromJson({"name": "Palau", "code": "PW"},
  Country.fromJson({"name": "Palestine", "code": "PS"},
  Country.fromJson({"name": "Panama", "code": "PA"},
  Country.fromJson({"name": "Papua New Guinea", "code": "PG"},
  Country.fromJson({"name": "Paraguay", "code": "PY"},
  Country.fromJson({"name": "Peru", "code": "PE"},
  Country.fromJson({"name": "Philippines", "code": "PH"},
  Country.fromJson({"name": "Pitcairn Islands", "code": "PN"},
  Country.fromJson({"name": "Poland", "code": "PL"},
  Country.fromJson({"name": "Portugal", "code": "PT"},
  Country.fromJson({"name": "Puerto Rico", "code": "PR"},
  Country.fromJson({"name": "Qatar", "code": "QA"},
  Country.fromJson({"name": "Reunion", "code": "RE"},
  Country.fromJson({"name": "Romania", "code": "RO"},
  Country.fromJson({"name": "Russia", "code": "RU"},
  Country.fromJson({"name": "Rwanda", "code": "RW"},
  Country.fromJson({"name": "Saint Helena", "code": "SH"},
  Country.fromJson({"name": "Saint Kitts and Nevis", "code": "KN"},
  Country.fromJson({"name": "Saint Lucia", "code": "LC"},
  Country.fromJson({"name": "Saint Pierre and Miquelon", "code": "PM"},
  Country.fromJson({"name": "Saint Vincent and the Grenadines", "code": "VC"},
  Country.fromJson({"name": "Samoa", "code": "WS"},
  Country.fromJson({"name": "San Marino", "code": "SM"},
  Country.fromJson({"name": "Sao Tome and Principe", "code": "ST"},
  Country.fromJson({"name": "Saudi Arabia", "code": "SA"},
  Country.fromJson({"name": "Senegal", "code": "SN"},
  Country.fromJson({"name": "Serbia", "code": "RS"},
  Country.fromJson({"name": "Montenegro", "code": "ME"},
  Country.fromJson({"name": "Kosovo", "code": "XK"},
  Country.fromJson({"name": "Seychelles", "code": "SC"},
  Country.fromJson({"name": "Sierra Leone", "code": "SL"},
  Country.fromJson({"name": "Singapore", "code": "SG"},
  Country.fromJson({"name": "Slovakia", "code": "SK"},
  Country.fromJson({"name": "Slovenia", "code": "SI"},
  Country.fromJson({"name": "Solomon Islands", "code": "SB"},
  Country.fromJson({"name": "Somalia", "code": "SO"},
  Country.fromJson({"name": "South Africa", "code": "ZA"},
  Country.fromJson({"name": "South Georgia and the South Sandwich Islands", "code": "GS"},
  Country.fromJson({"name": "Spain", "code": "ES"},
  Country.fromJson({"name": "Sri Lanka", "code": "LK"},
  Country.fromJson({"name": "Sudan", "code": "SD"},
  Country.fromJson({"name": "Suriname", "code": "SR"},
  Country.fromJson({"name": "Svalbard and Jan Mayen", "code": "SJ"},
  Country.fromJson({"name": "Swaziland", "code": "SZ"},
  Country.fromJson({"name": "Sweden", "code": "SE"},
  Country.fromJson({"name": "Switzerland", "code": "CH"},
  Country.fromJson({"name": "Syria", "code": "SY"},
  Country.fromJson({"name": "Taiwan", "code": "TW"},
  Country.fromJson({"name": "Tajikistan", "code": "TJ"},
  Country.fromJson({"name": "Tanzania", "code": "TZ"},
  Country.fromJson({"name": "Thailand", "code": "TH"},
  Country.fromJson({"name": "Timor-Leste", "code": "TL"},
  Country.fromJson({"name": "Togo", "code": "TG"},
  Country.fromJson({"name": "Tokelau", "code": "TK"},
  Country.fromJson({"name": "Tonga", "code": "TO"},
  Country.fromJson({"name": "Trinidad and Tobago", "code": "TT"},
  Country.fromJson({"name": "Tunisia", "code": "TN"},
  Country.fromJson({"name": "Turkey", "code": "TR"},
  Country.fromJson({"name": "Turkmenistan", "code": "TM"},
  Country.fromJson({"name": "Turks and Caicos Islands", "code": "TC"},
  Country.fromJson({"name": "Tuvalu", "code": "TV"},
  Country.fromJson({"name": "Uganda", "code": "UG"},
  Country.fromJson({"name": "Ukraine", "code": "UA"},
  Country.fromJson({"name": "United Arab Emirates", "code": "AE"},
  Country.fromJson({"name": "United Kingdom", "code": "GB"},
  Country.fromJson({"name": "United States", "code": "US"},
  Country.fromJson({"name": "United States Minor Outlying Islands", "code": "UM"},
  Country.fromJson({"name": "Uruguay", "code": "UY"},
  Country.fromJson({"name": "Uzbekistan", "code": "UZ"},
  Country.fromJson({"name": "Vanuatu", "code": "VU"},
  Country.fromJson({"name": "Venezuela", "code": "VE"},
  Country.fromJson({"name": "Vietnam", "code": "VN"},
  Country.fromJson({"name": "Virgin Islands, British", "code": "VG"},
  Country.fromJson({"name": "Virgin Islands, U.S.", "code": "VI"},
  Country.fromJson({"name": "Wallis and Futuna", "code": "WF"},
  Country.fromJson({"name": "Western Sahara", "code": "EH"},
  Country.fromJson({"name": "Yemen", "code": "YE"},
  Country.fromJson({"name": "Zambia", "code": "ZM"},
  Country.fromJson({"name": "Zimbabwe", "code": "ZN"}
];
*/
